services:
  qdrant:
    image: qdrant/qdrant:v1.11.0
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    networks: [rag-net]

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    env_file: .env
    depends_on: [qdrant]
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    networks: [rag-net]

  ui:
    build:
      context: .
      dockerfile: docker/Dockerfile.ui
    depends_on: [api]
    environment:
      - STREAMLIT_SERVER_PORT=8501
    ports:
      - "8501:8501"
    networks: [rag-net]

networks:
  rag-net: {}

volumes:
  qdrant_storage: {}
