FROM python:3.12-slim

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PIP_NO_CACHE_DIR=1

WORKDIR /ui

# Instala deps Python via requirements da própria pasta ui/
COPY ui/requirements.txt /ui/requirements.txt
RUN pip install --upgrade pip && pip install -r /ui/requirements.txt

# Copia o código da UI
COPY ui /ui

EXPOSE 8501
CMD ["streamlit","run","app.py","--server.port","8501","--server.address","0.0.0.0"]
